version: '3.8'

services:
  sentinel-simulator:
    build: .
    container_name: sentinel_nodes_simulator
    restart: unless-stopped
    environment:
      - SENTINEL_API_URL=${SENTINEL_API_URL:-https://sentinel.mguillermo.com/api/v1}
      - TELEMETRY_ENDPOINT=${TELEMETRY_ENDPOINT:-/telemetry/}
      - SEND_INTERVAL_SECONDS=${SEND_INTERVAL_SECONDS:-600}
      - MASTER_API_KEY=${MASTER_API_KEY:-sentinel_h2o_master_secret_2026}
      - ANOMALY_PROBABILITY=${ANOMALY_PROBABILITY:-0.08}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - API_KEY_NODO_01=${API_KEY_NODO_01:-sec_key_nodo_01_cabecera_67c935eec78775536188d962}
      - API_KEY_NODO_02=${API_KEY_NODO_02:-sec_key_ravira_secure_02}
      - API_KEY_NODO_03=${API_KEY_NODO_03:-sec_key_acos_secure_03}
      - API_KEY_NODO_04=${API_KEY_NODO_04:-sec_key_huando_secure_04}
      - API_KEY_NODO_05=${API_KEY_NODO_05:-sec_key_huayopampa_secure_05}
      - API_KEY_NODO_06=${API_KEY_NODO_06:-sec_key_chancay_secure_06}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
